// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: storage_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	GetCurrentBillName(ctx context.Context, in *GetCurrentBillNameRequest, opts ...grpc.CallOption) (*GetCurrentBillNameResponse, error)
	SetCurrentBillName(ctx context.Context, in *SetCurrentBillNameRequest, opts ...grpc.CallOption) (*SetCurrentBillNameResponse, error)
	ListAllBill(ctx context.Context, in *ListAllBillRequest, opts ...grpc.CallOption) (*ListAllBillResponse, error)
	GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*GetBillResponse, error)
	CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillResponse, error)
	DeleteBill(ctx context.Context, in *DeleteBillRequest, opts ...grpc.CallOption) (*DeleteBillResponse, error)
	ListAllDayEntry(ctx context.Context, in *ListAllDayEntryRequest, opts ...grpc.CallOption) (*ListAllDayEntryResponse, error)
	GetDayEntry(ctx context.Context, in *GetDayEntryRequest, opts ...grpc.CallOption) (*GetDayEntryResponse, error)
	CreateDayEntry(ctx context.Context, in *CreateDayEntryRequest, opts ...grpc.CallOption) (*CreateDayEntryResponse, error)
	DeleteDayEntry(ctx context.Context, in *DeleteDayEntryRequest, opts ...grpc.CallOption) (*DeleteDayEntryResponse, error)
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordEntryResponse, error)
	DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) GetCurrentBillName(ctx context.Context, in *GetCurrentBillNameRequest, opts ...grpc.CallOption) (*GetCurrentBillNameResponse, error) {
	out := new(GetCurrentBillNameResponse)
	err := c.cc.Invoke(ctx, "/StorageService/GetCurrentBillName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) SetCurrentBillName(ctx context.Context, in *SetCurrentBillNameRequest, opts ...grpc.CallOption) (*SetCurrentBillNameResponse, error) {
	out := new(SetCurrentBillNameResponse)
	err := c.cc.Invoke(ctx, "/StorageService/SetCurrentBillName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListAllBill(ctx context.Context, in *ListAllBillRequest, opts ...grpc.CallOption) (*ListAllBillResponse, error) {
	out := new(ListAllBillResponse)
	err := c.cc.Invoke(ctx, "/StorageService/ListAllBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*GetBillResponse, error) {
	out := new(GetBillResponse)
	err := c.cc.Invoke(ctx, "/StorageService/GetBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillResponse, error) {
	out := new(CreateBillResponse)
	err := c.cc.Invoke(ctx, "/StorageService/CreateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteBill(ctx context.Context, in *DeleteBillRequest, opts ...grpc.CallOption) (*DeleteBillResponse, error) {
	out := new(DeleteBillResponse)
	err := c.cc.Invoke(ctx, "/StorageService/DeleteBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListAllDayEntry(ctx context.Context, in *ListAllDayEntryRequest, opts ...grpc.CallOption) (*ListAllDayEntryResponse, error) {
	out := new(ListAllDayEntryResponse)
	err := c.cc.Invoke(ctx, "/StorageService/ListAllDayEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetDayEntry(ctx context.Context, in *GetDayEntryRequest, opts ...grpc.CallOption) (*GetDayEntryResponse, error) {
	out := new(GetDayEntryResponse)
	err := c.cc.Invoke(ctx, "/StorageService/GetDayEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateDayEntry(ctx context.Context, in *CreateDayEntryRequest, opts ...grpc.CallOption) (*CreateDayEntryResponse, error) {
	out := new(CreateDayEntryResponse)
	err := c.cc.Invoke(ctx, "/StorageService/CreateDayEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteDayEntry(ctx context.Context, in *DeleteDayEntryRequest, opts ...grpc.CallOption) (*DeleteDayEntryResponse, error) {
	out := new(DeleteDayEntryResponse)
	err := c.cc.Invoke(ctx, "/StorageService/DeleteDayEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, "/StorageService/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateRecord(ctx context.Context, in *CreateRecordRequest, opts ...grpc.CallOption) (*CreateRecordEntryResponse, error) {
	out := new(CreateRecordEntryResponse)
	err := c.cc.Invoke(ctx, "/StorageService/CreateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	out := new(DeleteRecordResponse)
	err := c.cc.Invoke(ctx, "/StorageService/DeleteRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility
type StorageServiceServer interface {
	GetCurrentBillName(context.Context, *GetCurrentBillNameRequest) (*GetCurrentBillNameResponse, error)
	SetCurrentBillName(context.Context, *SetCurrentBillNameRequest) (*SetCurrentBillNameResponse, error)
	ListAllBill(context.Context, *ListAllBillRequest) (*ListAllBillResponse, error)
	GetBill(context.Context, *GetBillRequest) (*GetBillResponse, error)
	CreateBill(context.Context, *CreateBillRequest) (*CreateBillResponse, error)
	DeleteBill(context.Context, *DeleteBillRequest) (*DeleteBillResponse, error)
	ListAllDayEntry(context.Context, *ListAllDayEntryRequest) (*ListAllDayEntryResponse, error)
	GetDayEntry(context.Context, *GetDayEntryRequest) (*GetDayEntryResponse, error)
	CreateDayEntry(context.Context, *CreateDayEntryRequest) (*CreateDayEntryResponse, error)
	DeleteDayEntry(context.Context, *DeleteDayEntryRequest) (*DeleteDayEntryResponse, error)
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	CreateRecord(context.Context, *CreateRecordRequest) (*CreateRecordEntryResponse, error)
	DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServiceServer struct {
}

func (UnimplementedStorageServiceServer) GetCurrentBillName(context.Context, *GetCurrentBillNameRequest) (*GetCurrentBillNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentBillName not implemented")
}
func (UnimplementedStorageServiceServer) SetCurrentBillName(context.Context, *SetCurrentBillNameRequest) (*SetCurrentBillNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCurrentBillName not implemented")
}
func (UnimplementedStorageServiceServer) ListAllBill(context.Context, *ListAllBillRequest) (*ListAllBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllBill not implemented")
}
func (UnimplementedStorageServiceServer) GetBill(context.Context, *GetBillRequest) (*GetBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBill not implemented")
}
func (UnimplementedStorageServiceServer) CreateBill(context.Context, *CreateBillRequest) (*CreateBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}
func (UnimplementedStorageServiceServer) DeleteBill(context.Context, *DeleteBillRequest) (*DeleteBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBill not implemented")
}
func (UnimplementedStorageServiceServer) ListAllDayEntry(context.Context, *ListAllDayEntryRequest) (*ListAllDayEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllDayEntry not implemented")
}
func (UnimplementedStorageServiceServer) GetDayEntry(context.Context, *GetDayEntryRequest) (*GetDayEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDayEntry not implemented")
}
func (UnimplementedStorageServiceServer) CreateDayEntry(context.Context, *CreateDayEntryRequest) (*CreateDayEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDayEntry not implemented")
}
func (UnimplementedStorageServiceServer) DeleteDayEntry(context.Context, *DeleteDayEntryRequest) (*DeleteDayEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDayEntry not implemented")
}
func (UnimplementedStorageServiceServer) GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedStorageServiceServer) CreateRecord(context.Context, *CreateRecordRequest) (*CreateRecordEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecord not implemented")
}
func (UnimplementedStorageServiceServer) DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_GetCurrentBillName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentBillNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetCurrentBillName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/GetCurrentBillName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetCurrentBillName(ctx, req.(*GetCurrentBillNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_SetCurrentBillName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCurrentBillNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).SetCurrentBillName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/SetCurrentBillName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).SetCurrentBillName(ctx, req.(*SetCurrentBillNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListAllBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListAllBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/ListAllBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListAllBill(ctx, req.(*ListAllBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/GetBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetBill(ctx, req.(*GetBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/CreateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateBill(ctx, req.(*CreateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/DeleteBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteBill(ctx, req.(*DeleteBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListAllDayEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllDayEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListAllDayEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/ListAllDayEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListAllDayEntry(ctx, req.(*ListAllDayEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetDayEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDayEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetDayEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/GetDayEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetDayEntry(ctx, req.(*GetDayEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateDayEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDayEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateDayEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/CreateDayEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateDayEntry(ctx, req.(*CreateDayEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteDayEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDayEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteDayEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/DeleteDayEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteDayEntry(ctx, req.(*DeleteDayEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/CreateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateRecord(ctx, req.(*CreateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService/DeleteRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteRecord(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentBillName",
			Handler:    _StorageService_GetCurrentBillName_Handler,
		},
		{
			MethodName: "SetCurrentBillName",
			Handler:    _StorageService_SetCurrentBillName_Handler,
		},
		{
			MethodName: "ListAllBill",
			Handler:    _StorageService_ListAllBill_Handler,
		},
		{
			MethodName: "GetBill",
			Handler:    _StorageService_GetBill_Handler,
		},
		{
			MethodName: "CreateBill",
			Handler:    _StorageService_CreateBill_Handler,
		},
		{
			MethodName: "DeleteBill",
			Handler:    _StorageService_DeleteBill_Handler,
		},
		{
			MethodName: "ListAllDayEntry",
			Handler:    _StorageService_ListAllDayEntry_Handler,
		},
		{
			MethodName: "GetDayEntry",
			Handler:    _StorageService_GetDayEntry_Handler,
		},
		{
			MethodName: "CreateDayEntry",
			Handler:    _StorageService_CreateDayEntry_Handler,
		},
		{
			MethodName: "DeleteDayEntry",
			Handler:    _StorageService_DeleteDayEntry_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _StorageService_GetRecord_Handler,
		},
		{
			MethodName: "CreateRecord",
			Handler:    _StorageService_CreateRecord_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _StorageService_DeleteRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage_service.proto",
}
